---
title: "Atmar modeling"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
To get observed viral shedding values from the Atmar et al. study, I data-mined
graphs using the R package metaDigitise.
```{r}
require(metaDigitise)

atmardata <- metaDigitise("~/Research Project/Summer URE/Process Images",
                            summary=FALSE)

atmardata= atmardata$scatterplot$plotd.jpg
```

These are all the functions I used to optimize parameters for the Li model I fit
to the Atmar data.
```{r}
sse.viralLoad <- function(params, data) {
  vl = log10(data$y)
  t = data$x * 24 - 19
  
  estimates= generate.estimates(params, t)
  
  sse= sum((estimates - vl)^2)
  
  if (sse > 1e20) {
    return(1e20)
  } else {
    return(sse)
  }
  
}

generate.estimates <- function(params, t) {
  
  p1= exp(params[1])
  p2= exp(params[2])
  p3= exp(params[3])
  p4= exp(params[4])
  
  estimate= (2 * p1) / (exp(-p2*(t-p3)) + exp(p4*(t-p3)))
  
  return(log10(estimate))
  
} 

get.params <- function(data) {
  
  fits= generate.possible.params(data)
  
  minsse= min(fits[fits$convergence==0, ]$sse)
  
  pars= unlist((fits[fits$sse == minsse, ])[1:4])
  
  return (c(pars, minsse))
}

generate.possible.params <- function(data) {
  numguess= 1e4
  
  fits= data.frame(matrix(NA, nrow = numguess, ncol = 6))
  
  colnames(fits)= c('p1','p2','p3','p4','convergence','sse')
  
  for (g in 1:numguess) {
    p1= runif(1, -1, log(1e12))
    p2= runif(1, -1, 1)
    p3= runif(1, -1, 4*24)
    p4= runif(1, -5, 1)
    
    params= c(p1, p2, p3, p4)
    
    fit= optim(params, sse.viralLoad, data=data)
    
    fits[g, ]= c(fit$par, fit$convergence, fit$value)
  }
  
  return(fits)
}

```


```{r}
plot.optimization <- function(data) {
  fits= generate.possible.params(data)
  t=data$x * 24 - 19
  vl=log10(data$y)
  
  sortedfits= fits[order(fits$sse),]
  
  colors= c()
  for(i in c(800, 500, 200, 150, 100, 50, 1)) {
    fit=sortedfits[i, ]
    params= c(fit$p1, fit$p2, fit$p3, fit$p4)
    predictedvl= generate.estimates(params, t)
    plot(t, vl, xlim=c(0, 260), ylim=c(0, 12), xlab="Hours Since Inoculation", 
         ylab="Viral Shedding (log10)")
    lines(t, predictedvl, col="navyblue")
    legend(200, 2, legend=c("Fit"), col="navyblue", lty=1)
  }
}

plot.viralload <- function(data, pars, sympdata, aggregated=TRUE) {
  
  if(data$dose[1] == '4800') {
    col="#E69F00"
  } else if (data$dose[1] == '48') {
    col="#871a6e" 
  } else if (data$dose[1] == '4.8') {
    col="#009E73"
  }
  
  t=data$x * 24 - 19
    
  vl= data$y
  
  cex=2
  
  if(aggregated) {
    points(t, log10(vl), col=col)
  } else {
    plot(t, log10(vl), col=col, xlim=c(0, 14 * 24 - 19), ylim=c(0, 12),
       main=paste("Participant ", data$id[1], " (", dose, " RT-PCR Units)", sep=""),
       xlab="", ylab="", cex.lab=cex, cex.axis=cex, cex.main=cex, 
       font.main=2, font.lab=2)
    
    mtext(text="Hours After Inoculation", side=1, line=4, cex=cex)
    mtext(text=expression(paste("Viral Shedding (", log[10], ")")), side=2, line=3, cex=cex)
    
    plot.symptoms(sympdata, dose)
  }
  
  linet =seq(min(data$x)*24-19, max(data$x)*24-19, by=1)
  plot.bestfit(pars, linet, col, sympdata)

}

plot.bestfit <- function(pars, linet, col, sympdata) {
  predictedvl= generate.estimates(pars, linet)
  
  lines(linet, predictedvl, col=col)
  
  symp.onset= mean(sympdata$symp.onset) * 24 - 19
  symp.end= symp.onset + mean(sympdata$symp.dur) * 24
  
  lines(linet[linet <= symp.end & linet >= symp.onset], 
        predictedvl[linet <= symp.end & linet >= symp.onset], 
        col=col, lwd=3)
}

plot.symptoms <- function(data, dose) {
  if(dose == 4800) {
    col="#E69F00"
  } else if (dose == 48) {
    col="#871a6e" 
  } else if (dose == 4.8) {
    col="#009E73"
  }
  
  #Study day 1 begins 5-6 hours postinoculation
  start= data$symp.onset * 24 - 19
  length= data$symp.dur * 24
  
  abline(v=c(start, start + length), lty=2, col=col)
}

delay.symponset.peakvl <- function(time, predictedvl, symp.onset) {
  peak.vl.time= time[which(predictedvl==max(predictedvl))]
  
  delay= peak.vl.time - (symp.onset * 24 - 19)
  
  return(delay)
}

plot.parameter.panel <- function(slope, cex, param, lab, p) {
  linecolor <- "orchid"
  slopex <- 3
  labx <- 1
  laby <- 17
  cex <- 2
  lwd <- 3
  bold <- 2
  xlab <- expression(paste(log[10], " Infectious Dose"))
  ylim <- c(-5, 20)
  
  plot(id, p1, xlab="", ylab="", 
       cex.lab=cex, cex.axis=cex, cex=cex, font.lab=bold, ylim=ylim)
  abline(p1.linreg, col=linecolor, lwd=lwd)
  text(slopex, laby, labels=paste("Slope:", slope), cex=cex, font=bold)
  text(labx, laby, labels=lab, cex=cex, font=bold)
  text(slopex, laby - 2, labels=paste("p: ", p), cex=cex, font=bold)
  mtext(text=xlab, side=1, line=4, cex=cex)
  mtext(text=expression(paste(log[10], param, sep=" ")), side=2, line=3, cex=cex)
}

atmarsymptoms <- read.csv('atmarsymptoms.csv')
atmardata <- read.csv('atmardata.csv')
patientparams <- read.csv("Atmar Patient Parameters.csv")

id <- atmarsymptoms$id

png("Atmar Modeling.png", width=900, height=800)

par(mar=c(5.1, 6.1, 4.1, 2.1))
plot(1, type="n", xlab='', ylab='', xlim=c(0, 336), ylim=c(6,12), cex.axis=2)

mtext(text="Hours After Inoculation", side=1, line=4, cex=2, font=2)
mtext(text=expression(bold(paste("Viral Shedding (", log[10], ")"))), side=2, line=3, cex=2)

#sse= data.frame("id"=id, "avg.sse"=rep(0, length(id)))
#delay= data.frame("id"=id, "delay"=rep(0, length(id)), "dose"=rep(0, length(id)))


#patients <- data.frame(matrix(NA, nrow = length(id), ncol = 7))
#colnames(patients)= c('patient','infectious dose','p1','p2','p3','p4', 'sse')
#row <- 1

for (i in id) {
  #Procuring best params by minimizing sse
  vldata= atmardata[atmardata$id == i, ]
  sympdata= atmarsymptoms[atmarsymptoms$id == i, ]
  dose=vldata$dose[1]
  
  params= log(unlist(patientparams[patientparams$patient==i, 4:7]))
  #patients[row, ] = c(i, vldata[1, ]$dose, params)
  #row = row + 1
  #minsse= params[5]

  t=vldata$x * 24 - 19
  #sse[sse$id==i, ]$avg.sse= minsse / length(t)
  #delay[delay$id==i, ]$delay= 
    #delay.symponset.peakvl(t, generate.estimates(params, t), sympdata$symp.onset)
  
  #delay[delay$id==i, ]$dose= dose
  
  #Plotting data points, Li and Handel/Holder model fit, and symptom onset/duration
  #png("Atmar703.png", width=800, height=800)
  #par(mar=c(5, 5, 4, 4))
  plot.viralload(vldata, params[1:4], vldata$id[1], sympdata)
  #text(280, 11, labels="C", cex=2, font=2)
  #dev.off()
}

legend(220, 11.3, 
       legend=c("4800 RT-PCR Units", "48 RT-PCR Units", "4.8 RT-PCR Units"), 
       lty= 1, col=c("#E69F00", "#871a6e", "#009E73"), lwd=3, cex=1.5, text.font=2)

dev.off()

#Plotting average viral shedding trajectory over time for each infectious dose
png("Atmar Modeling Averages.png", width=900, height=800)

par(mar=c(5.1, 6.1, 4.1, 2.1))
plot(1, type="n", xlab='', ylab='', xlim=c(0, 336), ylim=c(6,12), cex.axis=2)

mtext(text="Hours After Inoculation", side=1, line=4, cex=2, font=2)
mtext(text=expression(bold(paste("Viral Shedding (", log[10], ")"))), side=2, line=3, cex=2)

params4800 <- read.csv("Params 4800.csv")$x[1:4]
params48 <- read.csv("Params 48.csv")$x[1:4]
params4.8 <- read.csv("Params 4.8.csv")$x[1:4]

vldata4800 <- atmardata[atmardata$dose=='4800',]
vldata48 <- atmardata[atmardata$dose=='48',]
vldata4.8 <- atmardata[atmardata$dose=='4.8',]

sympdata4800 <- atmarsymptoms[atmarsymptoms$dose=='4800',]
sympdata48 <- atmarsymptoms[atmarsymptoms$dose=='48',]
sympdata4.8 <- atmarsymptoms[atmarsymptoms$dose=='4.8',]

plot.viralload(vldata4800, params4800, sympdata4800)

plot.viralload(vldata48, params48, sympdata48)

plot.viralload(vldata4.8, params4.8, sympdata4.8)

legend(220, 11.3, 
       legend=c("4800 RT-PCR Units", "48 RT-PCR Units", "4.8 RT-PCR Units"), 
       lty= 1, col=c("#E69F00", "#871a6e", "#009E73"), lwd=3, cex=1.5, text.font=2)

dev.off()
#Plotting the parameters against infectious dose
id <- log10(patientparams$infectious.dose)
p1 <- log10(patientparams$p1)
p2 <- log10(patientparams$p2)
p3 <- log10(patientparams$p3)
p4 <- log10(patientparams$p4)

p1.linreg <- lm(p1~id)
p2.linreg <- lm(p2~id)
p3.linreg <- lm(p3~id)
p4.linreg <- lm(p4~id)

p1.slope <- substring(summary(p1.linreg)$coefficients[2], 1, 6)
p2.slope <- substring(summary(p2.linreg)$coefficients[2], 1, 6)
p3.slope <- substring(summary(p3.linreg)$coefficients[2], 1, 6)
p4.slope <- substring(summary(p4.linreg)$coefficients[2], 1, 6)

png("Parameters vs. Infectious Dose.png", width = 900, height = 800)
par(mfrow=c(2, 2), mar=c(5.1, 5.1, 1, 2.1))

plot.parameter.panel(p1.slope, cex, "P1", "A)", 0.21)
plot.parameter.panel(p2.slope, cex, "P2", "B)", 0.408)
plot.parameter.panel(p3.slope, cex, "P3", "C)", 0.915)
plot.parameter.panel(p4.slope, cex, "P4", "D)", 0.407)

dev.off()

#Plotting patients 703, 722, and 724
patientexamples <- c('703', '722', '724')
label <- c("A)", "B)", "C)")

png("Example Atmar.png", width=800, height=800)
par(mfrow=c(2, 2), mar=c(5.1, 5.1, 4.1, 3.1))
for(i in 1:length(patientexamples)) {
  p=patientexamples[i]
  vldata= atmardata[atmardata$id == p, ]
  sympdata= atmarsymptoms[atmarsymptoms$id == p, ]
  dose=vldata$dose[1]
  params=unlist(patientparams[patientparams$patient==p,][4:7])
  print(params)
  plot.viralload(vldata, log(params), sympdata, aggregated=FALSE)
  text(280, 11, labels=label[i], font=2, cex=2)
}
dev.off()

#Finding out if peak viral load and other parameters significantly differ between doses

#peakvl <- data.frame(matrix(NA, nrow = length(id), ncol = 4))
#colnames(peakvl)= c('patient','dose', 'peakvl', 'peaktime')
#row <- 1

#for (patient in id) {
  #data= atmardata[atmardata$id==patient,]
  #linet =seq(min(data$x)*24-19, max(data$x)*24-19, by=1)
  #params=unlist(patientparams[patientparams$patient==patient,][4:7])
  #predictedvl= generate.estimates(log(params), linet)
  #peak.vl = max(predictedvl)
  
  #peakvl[row,]$patient= patient
  #peakvl[row,]$peakvl= peak.vl
  #peakvl[row,]$dose= data$dose[1]
  #peakvl[row,]$peaktime= linet[which(predictedvl==peak.vl)]
  #row = row + 1
#}

#peakvl <- write.csv(peakvl, "peakvl.csv")

peakvl <- read.csv("peakvl.csv")

#looking at peak vl predicted by the model
peakvl.aov <- summary(aov(peakvl$peakvl ~ peakvl$dose))

#looking at peak vl time predicted by the model
peaktime.aov <- summary(aov(peakvl$peaktime ~ peakvl$dose))

#looking at p1 parameter
p1.aov <- summary(aov(patientparams$p1 ~ patientparams$infectious.dose))

#looking at p2 parameter
p2.aov <- summary(aov(patientparams$p2 ~ patientparams$infectious.dose))

#looking at p3 parameter
p3.aov <- summary(aov(patientparams$p3 ~ patientparams$infectious.dose))

#looking at p4 parameter
p4.aov <- summary(aov(patientparams$p4 ~ patientparams$infectious.dose))

#Variance of peak vl between infectious doses
lowdose.peakvl.var <- var(peakvl[peakvl$dose=="4.8",]$peakvl)
meddose.peakvl.var <- var(peakvl[peakvl$dose=="48",]$peakvl)
highdose.peakvl.var <- var(peakvl[peakvl$dose=="4800",]$peakvl)

#Variance of peak vl time between infectious doses
lowdose.peakvltime.var <- var(peakvl[peakvl$dose=="4.8",]$peaktime)
meddose.peakvltime.var <- var(peakvl[peakvl$dose=="48",]$peaktime)
highdose.peakvltime.var <- var(peakvl[peakvl$dose=="4800",]$peaktime)

#Saving variance to csv file
variance <- data.frame(dose=c(4.8, 48, 4800), 
                       peakvl.var=c(lowdose.peakvl.var, 
                                    meddose.peakvl.var, 
                                    highdose.peakvl.var),
                       peaktime.var=c(lowdose.peakvltime.var, 
                                      meddose.peakvltime.var, 
                                      highdose.peakvltime.var))

write.csv(variance, "Variance in peakvl atmar.csv")

#Looking at significance of variance of peakvl and peakvltime between infectious doses
variance <- read.csv("Variance in peakvl atmar.csv")

peakvl.var.aov <- summary(aov(variance$peakvl.var ~ variance$dose))
peakvltime.var.aov <- summary(aov(variance$peaktime.var ~ variance$dose))
```