---
title: "CHI Trial Literature Review"
author: "Kayla Zhang, Damie Pak, Megan Greischar"
date: "2024-05-24"
output:
  bookdown::pdf_document2:
    toc: no
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warnings = FALSE)
```

```{r}
library(here)
```

Here we combine shedding and symptom onset data from the CHI trials we 
collected into one plot.
```{r, fig.height = 7.5, fig.width = 6.5}
plot.segment <- function(xstart, col, ypos, cex, symptoms, isindividual, citation) {
  
  if (isindividual) {
    points(xstart + 1, ypos, pch=8)
  } else {
  }
  
  text(x=15, y=ypos, labels=citation, cex=0.8, adj=1)
  points(xstart, ypos, pch=ifelse(symptoms, 15, 16), col=col, cex=cex)
  
}

plot.pane <- function(dat, axis.labels) {
  
  plot(0, 0, xlim=c(0, 15), ylim=c(0, max(nrow(rightpane), nrow(leftpane)) * 4) + 3, 
       col = "white", xlab= "", ylab='', yaxt='n',
       xaxt="n")
  
  axis(1, at=seq(0, 15, by=3), mgp=c(0, 0.4, 0), tck=-0.02, cex.axis=0.8)
  axis.ystart <- 0
  
  for (v in 1:length(unique(dat$virus))) {
    currvirusdat <- dat[dat$virus==unique(dat$virus)[v],]
    numrows <- nrow(currvirusdat)
    currviruscol <- cols.df[cols.df$virus == currvirusdat$virus[1],]$col
    
    for (i in 1:nrow(currvirusdat)) {
      row <- currvirusdat[i,]
      

      citation <- bquote(.(row$author)*italic(" et al.")*"," ~ .(row$year))
    
      
      if(row$shed.onset >= row$symptom.onset) {
        plot.segment(xstart=row$shed.onset, 
                   col=currviruscol, 
                   ypos=axis.ystart+i*4-2.25,
                   cex=1.8,
                   symptoms=FALSE,
                   isindividual=row$individual,
                   citation=citation)
        
        plot.segment(xstart=row$symptom.onset, 
                   col="grey", 
                   ypos=axis.ystart+i*4 - 2.25,
                   cex=0.9,
                   symptoms=TRUE,
                   isindividual=FALSE,
                   citation=NA)
      } else {
        
        plot.segment(xstart=row$shed.onset, 
                   col=currviruscol, 
                   ypos=axis.ystart+i*4-2.25,
                   cex=1.8,
                   symptoms=FALSE,
                   isindividual=FALSE,
                   citation=NA)
      
        plot.segment(xstart=row$symptom.onset, 
                   col="grey", 
                   ypos=axis.ystart+i*4 - 2.25,
                   cex=0.9,
                   symptoms=TRUE,
                   isindividual=row$individual,
                   citation=citation)
        
      }
    
    }
    
      axis.yend <- axis.ystart + numrows * 4
      
      text(-0.25, axis.yend + 1, axis.labels[v], col=currviruscol, pos=4,
           cex=0.8)

      axis(2, at=seq(axis.ystart, axis.yend, by=4), col=currviruscol, lwd.ticks=0, 
           labels=rep("", length(seq(axis.ystart, axis.yend, by=4))), las=2, col.axis=currviruscol)
      axis.ystart <- axis.yend + 2
  }
}

chidata <- read.csv(here('data', 'chistudies.csv'))

leftpane <- chidata[chidata$virus %in% c('Influenza A', 'Rhinovirus'),]
rightpane <- chidata[chidata$virus %in% c('Norovirus', 'RSV', 'SARS-CoV-2'),]
cols.df <- data.frame(virus = unique(chidata$virus), 
                      col = c("#401594",
                              "#009E73", 
                              "#D55E00",
                              "#56B4E9",
                              "#CC79A7"))

labels.left <- c("Influenza A", "Rhinovirus")

labels.right <- c("Norovirus", "RSV", "SARS-CoV-2")

{
  par(bty='n', mfrow=c(1, 2), oma=c(1, 0, 0, 0), mar=c(1.1, 0.5, 0, 0))
  plot.pane(leftpane, labels.left)
  legend(x=2.75, y=20,
         legend=c("Shedding onset", "Symptom onset",
                        "Individual onset\ndata"),
         pch=c(16, 15, 8), col=c("black", "grey", "black"),
         pt.cex=c(1.8, 0.9, 1), cex=0.7)
  mtext('Days post-inoculation', side=1, line=0, outer=TRUE,
        adj=0.5, cex=0.8)
  plot.pane(rightpane, labels.right)
}
```



